export const list =[
    {
       index:'1',
        path:'home',
        name:"Home",
    },
    {
        index:2,
        path:'about',
        name:"About",
    },
    {
        index:3,
        path:'services',
        name:"Services",
    },
    {
        index:4,
        path:'portfolio',
        name:"Portfolio",
    },
    {
        index:5,
        path:'team',
        name:"Team",
    },
    {
         index:6,
         path:'career',
         name:'Career'
    },
    {
        index:7,
        path:'contact',
        name:"Contact ",
    },
    {
        index:8,
        path:'faq',
        name:"FAQ ",
    },
]